version: "3"
services:
  flyway:
    image: flyway/flyway:6
    command: -url=jdbc:postgresql://db/example -schemas=public -user=postgres -password=password -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      POSTGRES_DB: example
    ports:
      - 15432:5432
